'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SyncroSim.DGSim.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Annual Harvest Population filter minimum age is greater than the maximum age..
        '''</summary>
        Friend ReadOnly Property DGSIM_ERROR_ANNUAL_HARVEST_POP_AGE() As String
            Get
                Return ResourceManager.GetString("DGSIM_ERROR_ANNUAL_HARVEST_POP_AGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annual harvest values must be between 0 and 100 if they are specified as percentages..
        '''</summary>
        Friend ReadOnly Property DGSIM_ERROR_ANNUAL_HARVEST_VALUES() As String
            Get
                Return ResourceManager.GetString("DGSIM_ERROR_ANNUAL_HARVEST_VALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must define at least one Age Class..
        '''</summary>
        Friend ReadOnly Property DGSIM_ERROR_NO_AGE_CLASSES() As String
            Get
                Return ResourceManager.GetString("DGSIM_ERROR_NO_AGE_CLASSES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must define at least one Stratum..
        '''</summary>
        Friend ReadOnly Property DGSIM_ERROR_NO_STRATA() As String
            Get
                Return ResourceManager.GetString("DGSIM_ERROR_NO_STRATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot get random Beta value.  The standard deviation is too large given the specified mean, min and max: Mean {0:N4}, SD {1:N4}, Min {2:N4}, Max {3:N4}..
        '''</summary>
        Friend ReadOnly Property DGSIM_ERROR_RANDOM_BETA() As String
            Get
                Return ResourceManager.GetString("DGSIM_ERROR_RANDOM_BETA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend ReadOnly Property DGSIM_TIMESTEP() As String
            Get
                Return ResourceManager.GetString("DGSIM_TIMESTEP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Age Class Ranges were not specified.  Using default..
        '''</summary>
        Friend ReadOnly Property DGSIM_WARNING_USING_DEFAULT_AGE_CLASS_RANGES() As String
            Get
                Return ResourceManager.GetString("DGSIM_WARNING_USING_DEFAULT_AGE_CLASS_RANGES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Initial Population Distribution was not specified.  Using default..
        '''</summary>
        Friend ReadOnly Property DGSIM_WARNING_USING_DEFAULT_INITIAL_POP_DISTRIBUTION() As String
            Get
                Return ResourceManager.GetString("DGSIM_WARNING_USING_DEFAULT_INITIAL_POP_DISTRIBUTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Initial Population Size was not specified.  Using default..
        '''</summary>
        Friend ReadOnly Property DGSIM_WARNING_USING_DEFAULT_INITIAL_POP_SIZE() As String
            Get
                Return ResourceManager.GetString("DGSIM_WARNING_USING_DEFAULT_INITIAL_POP_SIZE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The number of iterations was not specified.  Using default..
        '''</summary>
        Friend ReadOnly Property DGSIM_WARNING_USING_DEFAULT_ITERATIONS() As String
            Get
                Return ResourceManager.GetString("DGSIM_WARNING_USING_DEFAULT_ITERATIONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The start Julian Day was not specified.  Using default..
        '''</summary>
        Friend ReadOnly Property DGSIM_WARNING_USING_DEFAULT_JDAY() As String
            Get
                Return ResourceManager.GetString("DGSIM_WARNING_USING_DEFAULT_JDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The number of timesteps was not specified.  Using default..
        '''</summary>
        Friend ReadOnly Property DGSIM_WARNING_USING_DEFAULT_TIMESTEPS() As String
            Get
                Return ResourceManager.GetString("DGSIM_WARNING_USING_DEFAULT_TIMESTEPS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
